// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package main

import (
	"time"
)

type AccountInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type DeleteProductResponse struct {
	DeletedID string  `json:"deletedId"`
	Success   bool    `json:"success"`
	Message   *string `json:"message,omitempty"`
}

type Mutation struct {
}

type Order struct {
	ID         string            `json:"id"`
	CreatedAt  time.Time         `json:"createdAt"`
	TotalPrice float64           `json:"totalPrice"`
	Products   []*OrderedProduct `json:"products"`
	Status     string            `json:"status"`
}

type OrderInput struct {
	AccountID string               `json:"accountId"`
	Products  []*OrderProductInput `json:"products"`
}

type OrderProductInput struct {
	ID       string `json:"id"`
	Quantity int    `json:"quantity"`
}

type OrderedProduct struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
	Quantity    int     `json:"quantity"`
}

type PaginationInput struct {
	Skip *int `json:"skip,omitempty"`
	Take *int `json:"take,omitempty"`
}

type Product struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
	Image       string  `json:"image"`
}

type ProductInput struct {
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
	Image       string  `json:"image"`
}

type Query struct {
}

type Review struct {
	ID        string    `json:"id"`
	ProductID string    `json:"productId"`
	AccountID string    `json:"accountId"`
	Content   *string   `json:"content,omitempty"`
	Rating    int       `json:"rating"`
	CreatedAt time.Time `json:"createdAt"`
}

type ReviewInput struct {
	ProductID string  `json:"productId"`
	AccountID string  `json:"accountId"`
	Content   *string `json:"content,omitempty"`
	Rating    int     `json:"rating"`
}
