// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package main

import (
	"time"
)

type AccountInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Cart struct {
	ID          string  `json:"id"`
	Quantity    float64 `json:"quantity"`
	Name        string  `json:"name"`
	Price       float64 `json:"price"`
	Description string  `json:"description"`
}

type CartInput struct {
	ProductID string  `json:"productId"`
	AccountID string  `json:"accountId"`
	Quantity  float64 `json:"quantity"`
}

type DeleteResponse struct {
	DeletedID string `json:"deletedId"`
	Success   bool   `json:"success"`
	Message   string `json:"message"`
}

type EditeAccountInput struct {
	Name     *string `json:"name,omitempty"`
	Email    *string `json:"email,omitempty"`
	Password *string `json:"password,omitempty"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Order struct {
	ID         string            `json:"id"`
	CreatedAt  time.Time         `json:"createdAt"`
	TotalPrice float64           `json:"totalPrice"`
	Products   []*OrderedProduct `json:"products"`
	Status     string            `json:"status"`
}

type OrderInput struct {
	AccountID string               `json:"accountId"`
	Products  []*OrderProductInput `json:"products"`
}

type OrderProductInput struct {
	ID       string `json:"id"`
	Quantity int    `json:"quantity"`
}

type OrderedProduct struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
	Quantity    int     `json:"quantity"`
}

type PaginationInput struct {
	Skip *int `json:"skip,omitempty"`
	Take *int `json:"take,omitempty"`
}

type Product struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
	Image       string  `json:"image"`
}

type ProductInput struct {
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
	Image       string  `json:"image"`
}

type Query struct {
}

type Review struct {
	ID        string    `json:"id"`
	Content   *string   `json:"content,omitempty"`
	Rating    int       `json:"rating"`
	Account   *Account  `json:"Account"`
	Product   *Product  `json:"Product"`
	CreatedAt time.Time `json:"createdAt"`
}

type ReviewInput struct {
	ProductID string  `json:"productId"`
	AccountID string  `json:"accountId"`
	Content   *string `json:"content,omitempty"`
	Rating    int     `json:"rating"`
}

type Token struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	ExpiresIn    int    `json:"expiresIn"`
}

type AuthResponse struct {
	ID           string `json:"id"`
	Email        string `json:"email"`
	BackendToken *Token `json:"backendToken"`
}
