// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: review.proto

package genproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Checkout struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	ProductIds    []string               `protobuf:"bytes,3,rep,name=productIds,proto3" json:"productIds,omitempty"`
	TotalPrice    float64                `protobuf:"fixed64,4,opt,name=totalPrice,proto3" json:"totalPrice,omitempty"`
	Image         string                 `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Checkout) Reset() {
	*x = Checkout{}
	mi := &file_review_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Checkout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Checkout) ProtoMessage() {}

func (x *Checkout) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Checkout.ProtoReflect.Descriptor instead.
func (*Checkout) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{0}
}

func (x *Checkout) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Checkout) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Checkout) GetProductIds() []string {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

func (x *Checkout) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *Checkout) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type PostCheckoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ProductIds    []string               `protobuf:"bytes,2,rep,name=productIds,proto3" json:"productIds,omitempty"`
	TotalPrice    float64                `protobuf:"fixed64,3,opt,name=totalPrice,proto3" json:"totalPrice,omitempty"`
	Image         string                 `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostCheckoutRequest) Reset() {
	*x = PostCheckoutRequest{}
	mi := &file_review_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostCheckoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostCheckoutRequest) ProtoMessage() {}

func (x *PostCheckoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostCheckoutRequest.ProtoReflect.Descriptor instead.
func (*PostCheckoutRequest) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{1}
}

func (x *PostCheckoutRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PostCheckoutRequest) GetProductIds() []string {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

func (x *PostCheckoutRequest) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *PostCheckoutRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type PostCheckoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Checkout      *Checkout              `protobuf:"bytes,1,opt,name=checkout,proto3" json:"checkout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostCheckoutResponse) Reset() {
	*x = PostCheckoutResponse{}
	mi := &file_review_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostCheckoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostCheckoutResponse) ProtoMessage() {}

func (x *PostCheckoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostCheckoutResponse.ProtoReflect.Descriptor instead.
func (*PostCheckoutResponse) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{2}
}

func (x *PostCheckoutResponse) GetCheckout() *Checkout {
	if x != nil {
		return x.Checkout
	}
	return nil
}

type GetCheckoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCheckoutRequest) Reset() {
	*x = GetCheckoutRequest{}
	mi := &file_review_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCheckoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCheckoutRequest) ProtoMessage() {}

func (x *GetCheckoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCheckoutRequest.ProtoReflect.Descriptor instead.
func (*GetCheckoutRequest) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{3}
}

func (x *GetCheckoutRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetCheckoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Checkout      *Checkout              `protobuf:"bytes,1,opt,name=checkout,proto3" json:"checkout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCheckoutResponse) Reset() {
	*x = GetCheckoutResponse{}
	mi := &file_review_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCheckoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCheckoutResponse) ProtoMessage() {}

func (x *GetCheckoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCheckoutResponse.ProtoReflect.Descriptor instead.
func (*GetCheckoutResponse) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{4}
}

func (x *GetCheckoutResponse) GetCheckout() *Checkout {
	if x != nil {
		return x.Checkout
	}
	return nil
}

type GetCheckoutsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skip          uint64                 `protobuf:"varint,1,opt,name=skip,proto3" json:"skip,omitempty"`
	Take          uint64                 `protobuf:"varint,2,opt,name=take,proto3" json:"take,omitempty"`
	Ids           []string               `protobuf:"bytes,3,rep,name=ids,proto3" json:"ids,omitempty"`
	Query         string                 `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCheckoutsRequest) Reset() {
	*x = GetCheckoutsRequest{}
	mi := &file_review_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCheckoutsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCheckoutsRequest) ProtoMessage() {}

func (x *GetCheckoutsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCheckoutsRequest.ProtoReflect.Descriptor instead.
func (*GetCheckoutsRequest) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{5}
}

func (x *GetCheckoutsRequest) GetSkip() uint64 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *GetCheckoutsRequest) GetTake() uint64 {
	if x != nil {
		return x.Take
	}
	return 0
}

func (x *GetCheckoutsRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *GetCheckoutsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type DeleteCheckoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCheckoutRequest) Reset() {
	*x = DeleteCheckoutRequest{}
	mi := &file_review_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCheckoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCheckoutRequest) ProtoMessage() {}

func (x *DeleteCheckoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCheckoutRequest.ProtoReflect.Descriptor instead.
func (*DeleteCheckoutRequest) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteCheckoutRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetCheckoutsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Checkouts     []*Checkout            `protobuf:"bytes,1,rep,name=checkouts,proto3" json:"checkouts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCheckoutsResponse) Reset() {
	*x = GetCheckoutsResponse{}
	mi := &file_review_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCheckoutsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCheckoutsResponse) ProtoMessage() {}

func (x *GetCheckoutsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCheckoutsResponse.ProtoReflect.Descriptor instead.
func (*GetCheckoutsResponse) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{7}
}

func (x *GetCheckoutsResponse) GetCheckouts() []*Checkout {
	if x != nil {
		return x.Checkouts
	}
	return nil
}

type DeleteCheckoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	DeletedID     string                 `protobuf:"bytes,3,opt,name=deletedID,proto3" json:"deletedID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCheckoutResponse) Reset() {
	*x = DeleteCheckoutResponse{}
	mi := &file_review_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCheckoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCheckoutResponse) ProtoMessage() {}

func (x *DeleteCheckoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCheckoutResponse.ProtoReflect.Descriptor instead.
func (*DeleteCheckoutResponse) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteCheckoutResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeleteCheckoutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteCheckoutResponse) GetDeletedID() string {
	if x != nil {
		return x.DeletedID
	}
	return ""
}

var File_review_proto protoreflect.FileDescriptor

const file_review_proto_rawDesc = "" +
	"\n" +
	"\freview.proto\x12\bgenproto\"\x88\x01\n" +
	"\bCheckout\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\x12\x1e\n" +
	"\n" +
	"productIds\x18\x03 \x03(\tR\n" +
	"productIds\x12\x1e\n" +
	"\n" +
	"totalPrice\x18\x04 \x01(\x01R\n" +
	"totalPrice\x12\x14\n" +
	"\x05image\x18\x05 \x01(\tR\x05image\"\x83\x01\n" +
	"\x13PostCheckoutRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x1e\n" +
	"\n" +
	"productIds\x18\x02 \x03(\tR\n" +
	"productIds\x12\x1e\n" +
	"\n" +
	"totalPrice\x18\x03 \x01(\x01R\n" +
	"totalPrice\x12\x14\n" +
	"\x05image\x18\x04 \x01(\tR\x05image\"F\n" +
	"\x14PostCheckoutResponse\x12.\n" +
	"\bcheckout\x18\x01 \x01(\v2\x12.genproto.CheckoutR\bcheckout\"$\n" +
	"\x12GetCheckoutRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"E\n" +
	"\x13GetCheckoutResponse\x12.\n" +
	"\bcheckout\x18\x01 \x01(\v2\x12.genproto.CheckoutR\bcheckout\"e\n" +
	"\x13GetCheckoutsRequest\x12\x12\n" +
	"\x04skip\x18\x01 \x01(\x04R\x04skip\x12\x12\n" +
	"\x04take\x18\x02 \x01(\x04R\x04take\x12\x10\n" +
	"\x03ids\x18\x03 \x03(\tR\x03ids\x12\x14\n" +
	"\x05query\x18\x04 \x01(\tR\x05query\"'\n" +
	"\x15DeleteCheckoutRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"H\n" +
	"\x14GetCheckoutsResponse\x120\n" +
	"\tcheckouts\x18\x01 \x03(\v2\x12.genproto.CheckoutR\tcheckouts\"j\n" +
	"\x16DeleteCheckoutResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x1c\n" +
	"\tdeletedID\x18\x03 \x01(\tR\tdeletedID2\xd0\x02\n" +
	"\x0fCheckoutService\x12M\n" +
	"\fPostCheckout\x12\x1d.genproto.PostCheckoutRequest\x1a\x1e.genproto.PostCheckoutResponse\x12J\n" +
	"\vGetCheckout\x12\x1c.genproto.GetCheckoutRequest\x1a\x1d.genproto.GetCheckoutResponse\x12M\n" +
	"\fGetCheckouts\x12\x1d.genproto.GetCheckoutsRequest\x1a\x1e.genproto.GetCheckoutsResponse\x12S\n" +
	"\x0eDeleteCheckout\x12\x1f.genproto.DeleteCheckoutRequest\x1a .genproto.DeleteCheckoutResponseB,Z*github.com/wignn/micro-3/checkout/genprotob\x06proto3"

var (
	file_review_proto_rawDescOnce sync.Once
	file_review_proto_rawDescData []byte
)

func file_review_proto_rawDescGZIP() []byte {
	file_review_proto_rawDescOnce.Do(func() {
		file_review_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_review_proto_rawDesc), len(file_review_proto_rawDesc)))
	})
	return file_review_proto_rawDescData
}

var file_review_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_review_proto_goTypes = []any{
	(*Checkout)(nil),               // 0: genproto.Checkout
	(*PostCheckoutRequest)(nil),    // 1: genproto.PostCheckoutRequest
	(*PostCheckoutResponse)(nil),   // 2: genproto.PostCheckoutResponse
	(*GetCheckoutRequest)(nil),     // 3: genproto.GetCheckoutRequest
	(*GetCheckoutResponse)(nil),    // 4: genproto.GetCheckoutResponse
	(*GetCheckoutsRequest)(nil),    // 5: genproto.GetCheckoutsRequest
	(*DeleteCheckoutRequest)(nil),  // 6: genproto.DeleteCheckoutRequest
	(*GetCheckoutsResponse)(nil),   // 7: genproto.GetCheckoutsResponse
	(*DeleteCheckoutResponse)(nil), // 8: genproto.DeleteCheckoutResponse
}
var file_review_proto_depIdxs = []int32{
	0, // 0: genproto.PostCheckoutResponse.checkout:type_name -> genproto.Checkout
	0, // 1: genproto.GetCheckoutResponse.checkout:type_name -> genproto.Checkout
	0, // 2: genproto.GetCheckoutsResponse.checkouts:type_name -> genproto.Checkout
	1, // 3: genproto.CheckoutService.PostCheckout:input_type -> genproto.PostCheckoutRequest
	3, // 4: genproto.CheckoutService.GetCheckout:input_type -> genproto.GetCheckoutRequest
	5, // 5: genproto.CheckoutService.GetCheckouts:input_type -> genproto.GetCheckoutsRequest
	6, // 6: genproto.CheckoutService.DeleteCheckout:input_type -> genproto.DeleteCheckoutRequest
	2, // 7: genproto.CheckoutService.PostCheckout:output_type -> genproto.PostCheckoutResponse
	4, // 8: genproto.CheckoutService.GetCheckout:output_type -> genproto.GetCheckoutResponse
	7, // 9: genproto.CheckoutService.GetCheckouts:output_type -> genproto.GetCheckoutsResponse
	8, // 10: genproto.CheckoutService.DeleteCheckout:output_type -> genproto.DeleteCheckoutResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_review_proto_init() }
func file_review_proto_init() {
	if File_review_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_review_proto_rawDesc), len(file_review_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_review_proto_goTypes,
		DependencyIndexes: file_review_proto_depIdxs,
		MessageInfos:      file_review_proto_msgTypes,
	}.Build()
	File_review_proto = out.File
	file_review_proto_goTypes = nil
	file_review_proto_depIdxs = nil
}
