// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: review.proto

package genproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CheckoutService_PostCheckout_FullMethodName   = "/genproto.CheckoutService/PostCheckout"
	CheckoutService_GetCheckout_FullMethodName    = "/genproto.CheckoutService/GetCheckout"
	CheckoutService_GetCheckouts_FullMethodName   = "/genproto.CheckoutService/GetCheckouts"
	CheckoutService_DeleteCheckout_FullMethodName = "/genproto.CheckoutService/DeleteCheckout"
)

// CheckoutServiceClient is the client API for CheckoutService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CheckoutServiceClient interface {
	PostCheckout(ctx context.Context, in *PostCheckoutRequest, opts ...grpc.CallOption) (*PostCheckoutResponse, error)
	GetCheckout(ctx context.Context, in *GetCheckoutRequest, opts ...grpc.CallOption) (*GetCheckoutResponse, error)
	GetCheckouts(ctx context.Context, in *GetCheckoutsRequest, opts ...grpc.CallOption) (*GetCheckoutsResponse, error)
	DeleteCheckout(ctx context.Context, in *DeleteCheckoutRequest, opts ...grpc.CallOption) (*DeleteCheckoutResponse, error)
}

type checkoutServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCheckoutServiceClient(cc grpc.ClientConnInterface) CheckoutServiceClient {
	return &checkoutServiceClient{cc}
}

func (c *checkoutServiceClient) PostCheckout(ctx context.Context, in *PostCheckoutRequest, opts ...grpc.CallOption) (*PostCheckoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostCheckoutResponse)
	err := c.cc.Invoke(ctx, CheckoutService_PostCheckout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkoutServiceClient) GetCheckout(ctx context.Context, in *GetCheckoutRequest, opts ...grpc.CallOption) (*GetCheckoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCheckoutResponse)
	err := c.cc.Invoke(ctx, CheckoutService_GetCheckout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkoutServiceClient) GetCheckouts(ctx context.Context, in *GetCheckoutsRequest, opts ...grpc.CallOption) (*GetCheckoutsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCheckoutsResponse)
	err := c.cc.Invoke(ctx, CheckoutService_GetCheckouts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkoutServiceClient) DeleteCheckout(ctx context.Context, in *DeleteCheckoutRequest, opts ...grpc.CallOption) (*DeleteCheckoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCheckoutResponse)
	err := c.cc.Invoke(ctx, CheckoutService_DeleteCheckout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CheckoutServiceServer is the server API for CheckoutService service.
// All implementations must embed UnimplementedCheckoutServiceServer
// for forward compatibility.
type CheckoutServiceServer interface {
	PostCheckout(context.Context, *PostCheckoutRequest) (*PostCheckoutResponse, error)
	GetCheckout(context.Context, *GetCheckoutRequest) (*GetCheckoutResponse, error)
	GetCheckouts(context.Context, *GetCheckoutsRequest) (*GetCheckoutsResponse, error)
	DeleteCheckout(context.Context, *DeleteCheckoutRequest) (*DeleteCheckoutResponse, error)
	mustEmbedUnimplementedCheckoutServiceServer()
}

// UnimplementedCheckoutServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCheckoutServiceServer struct{}

func (UnimplementedCheckoutServiceServer) PostCheckout(context.Context, *PostCheckoutRequest) (*PostCheckoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostCheckout not implemented")
}
func (UnimplementedCheckoutServiceServer) GetCheckout(context.Context, *GetCheckoutRequest) (*GetCheckoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCheckout not implemented")
}
func (UnimplementedCheckoutServiceServer) GetCheckouts(context.Context, *GetCheckoutsRequest) (*GetCheckoutsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCheckouts not implemented")
}
func (UnimplementedCheckoutServiceServer) DeleteCheckout(context.Context, *DeleteCheckoutRequest) (*DeleteCheckoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCheckout not implemented")
}
func (UnimplementedCheckoutServiceServer) mustEmbedUnimplementedCheckoutServiceServer() {}
func (UnimplementedCheckoutServiceServer) testEmbeddedByValue()                         {}

// UnsafeCheckoutServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CheckoutServiceServer will
// result in compilation errors.
type UnsafeCheckoutServiceServer interface {
	mustEmbedUnimplementedCheckoutServiceServer()
}

func RegisterCheckoutServiceServer(s grpc.ServiceRegistrar, srv CheckoutServiceServer) {
	// If the following call pancis, it indicates UnimplementedCheckoutServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CheckoutService_ServiceDesc, srv)
}

func _CheckoutService_PostCheckout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostCheckoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckoutServiceServer).PostCheckout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckoutService_PostCheckout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckoutServiceServer).PostCheckout(ctx, req.(*PostCheckoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckoutService_GetCheckout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCheckoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckoutServiceServer).GetCheckout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckoutService_GetCheckout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckoutServiceServer).GetCheckout(ctx, req.(*GetCheckoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckoutService_GetCheckouts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCheckoutsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckoutServiceServer).GetCheckouts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckoutService_GetCheckouts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckoutServiceServer).GetCheckouts(ctx, req.(*GetCheckoutsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckoutService_DeleteCheckout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCheckoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckoutServiceServer).DeleteCheckout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckoutService_DeleteCheckout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckoutServiceServer).DeleteCheckout(ctx, req.(*DeleteCheckoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CheckoutService_ServiceDesc is the grpc.ServiceDesc for CheckoutService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CheckoutService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "genproto.CheckoutService",
	HandlerType: (*CheckoutServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostCheckout",
			Handler:    _CheckoutService_PostCheckout_Handler,
		},
		{
			MethodName: "GetCheckout",
			Handler:    _CheckoutService_GetCheckout_Handler,
		},
		{
			MethodName: "GetCheckouts",
			Handler:    _CheckoutService_GetCheckouts_Handler,
		},
		{
			MethodName: "DeleteCheckout",
			Handler:    _CheckoutService_DeleteCheckout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "review.proto",
}
